# Generated by Django 3.2.3 on 2021-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='type',
            field=models.CharField(default='desconocido', max_length=200, null=True, verbose_name='tipo de producto'),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='desconocido', max_length=200, null=True, verbose_name='tipo de producto'),
        ),
    ]
